### PR TITLE
move from links to networks

### PR DESCRIPTION
**Pull request by icyflame**
links is deprecated in Docker: https://docs.docker.com/network/links/

image

This is the network diagram (the arrows represent the old links, and the annotations near the arrows represent the name of the network that allows those connections)

Imgur

I tested this by running docker-compose locally, and then opening the wiki and making an edit / checking that pages were there. (I used a mysql backup of the wiki to test this stuff)

### CODE REVIEW

**Comment by icyflame** [comment]
For some reason, GitHub is displaying my image rotated. The actual image has the proper orientation. Strange.

Anyway, changed the link to one on Imgur.

**Comment by sam17** [comment]
Why not used `depends_on` ? Also, we seem to not have health status for the container to check if they are up. We should add them maybe?

**Comment by icyflame** [comment]
@sam17 Why do you want to use `depends_on`? 🤔  These are simply connected over the network. If the other container is down, the app won't work. But there is no need to start them in a particular sequence.

(I don't know about the health status feature, can you please open an issue describing how it might help us? 🙌 )

**Comment by thealphadollar** [comment]
@icyflame @sam17 Please update.

**Review by amrav — APPROVED** [review]

**Pull request merged**
