### PR TITLE
Added Nuke extension

### PR DESCRIPTION
**Pull request by DefCon-007**

### CODE REVIEW

**Comment by amrav** [comment]
Thanks for opening a PR! CI indicates that there's a problem with the patch - could you investigate why?

**Comment by DefCon-007** [comment]
It is failing with this error `mv: cannot move 'Nuke' to '/srv/mediawiki/extensions/Nuke': Directory not empty` which is weird because it is working for all other extensions. 
Also I was thinking how about we add the tar files of all the extensions in place of downloading them?

**Comment by amrav** [comment]
Yes. Why do you think that could be happening? Have you tried running this
on your local laptop, and investigating why it thinks the directory is not
empty?

**Comment by DefCon-007** [comment]
Apparently in the `/Extensions` Nuke is already present but I was trying to access the Nuke extension form `https://wiki.metakgp.org/Special:Nuke` that's why I was getting nginx error.

**Pull request closed without merging**
