### PR TITLE
Use ReCaptcha (NoCaptcha) instead of QuestyCaptcha

### PR DESCRIPTION
**Pull request by icyflame**
We have been having some problems with our setup of `QuestyCaptcha`. We would like to try MathCaptcha and see if that improves the experience of actual contributors.

This captcha challenge is less aggresive than QuestyCaptcha and might cause spam to increase. We will monitor this as well.

## New captcha

The Captcha can't be tested locally because localhost isn't in the supported domain list for the recaptcha key that we are using.

image

[1]: https://www.mediawiki.org/wiki/Extension:Math

### CODE REVIEW

**Review by thealphadollar — CHANGES_REQUESTED** [review]
The diff is not loading for me :cry: Too many file changes. I've taken note of the changes required. Also, it is important to Update the same in the readme; in case we need to change captcha in the future as well.

Can you please add a note on what steps to take for modifying method of captcha in the RUNBOOK.md?

**Comment by thealphadollar** [comment]
@icyflame Can you please add instructions on how one can go about changing the captcha type in the RUNBOOK?

**Comment by icyflame** [comment]
@thealphadollar I don't think that's information that should be in the Runbook. The Runbook is only for commands that can be run in production to do something. Changing the captcha is a feature change that should just be done using old PRs and other documentation as reference.

**Review by amrav — APPROVED** [review]

**Review by thealphadollar — APPROVED** [review]
LGTM.

@icyflame I added a short section in README.md

**Pull request merged**
