### PR TITLE
fix: check number of wiki backup files on dropbox

### PR DESCRIPTION
**Pull request by shikharish**

### CODE REVIEW

**Comment by harshkhandeparkar** [comment]
What does this fix?

**Comment by shikharish** [comment]
the dropbox account may contain other backup files as well. there was an error in counting the number of wiki backup files.

**Comment by harshkhandeparkar** [comment]
Isn't the file directory scoped for the application?

**Comment by shikharish** [comment]
No, we are storing all backups in the root directory of thr dropbox account

**Comment by harshkhandeparkar** [comment]
> No, we are storing all backups in the root directory of thr dropbox account

They are in the root directory of the dropbox app right? For different projects we can make a different app and it will be in its own folder.

**Comment by shikharish** [comment]
> > No, we are storing all backups in the root directory of thr dropbox account
> 
> They are in the root directory of the dropbox app right? For different projects we can make a different app and it will be in its own folder.

We access the dropbox account using a dropbox app. I don't think it creates a new folder unless we explicitly do so.

**Comment by harshkhandeparkar** [comment]
> > > No, we are storing all backups in the root directory of thr dropbox account
> > 
> > 
> > They are in the root directory of the dropbox app right? For different projects we can make a different app and it will be in its own folder.
> 
> We access the dropbox account using a dropbox app. I don't think it creates a new folder unless we explicitly do so.

image
But there is a folder...

**Review by proffapt — APPROVED** [review]
Checks are important, thanks.

**Review by harshkhandeparkar — APPROVED** [review]

**Pull request merged**
