### PR TITLE
Update mediawiki to 1.32.2

### PR DESCRIPTION
**Pull request by thealphadollar**
- Version 1.30 is no more supported
- Update extensions accordingly

I'll use the following procedure once the PR is approved to update on prod.

- Take the latest backup of the server and store it locally.
- `git pull` and `docker-compose build`
- `docker-compose down`
- `docker volume rm <mediawiki-volume`
- `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.prod.yml up --build -d`
- `docker-compose exec php /srv/mediawiki/maintenance/update.php`

@icyflame Please have a thorough look.

References:
- https://www.mediawiki.org/wiki/Manual:Upgrading

### CODE REVIEW

**Comment by thealphadollar** [comment]
The test is failing since at the moment this page is not working: 

https://www.mediawiki.org/wiki/Special:ExtensionDistributor

Screenshot from 2019-06-15 17-48-32

**Comment by amrav** [comment]
When doing an upgrade or restart, you don't need to restore from backup
(you should still definitely take the backup in case anything goes wrong).
The database is on the mysql volume, which persists through the upgrade.

I think the containers need to be running before you can run update.php,
and the docker-compose command needs to be fed the prod configuration files
(there's an example in the runbook).

**Comment by thealphadollar** [comment]
> When doing an upgrade or restart, you don't need to restore from backup (you should still definitely take the backup in case anything goes wrong). The database is on the mysql volume, which persists through the upgrade. I think the containers need to be running before you can run update.php, and the docker-compose command needs to be fed the prod configuration files (there's an example in the runbook).

I've updated the instructions; please have a look.

**Review by icyflame — COMMENTED** [review]
Good work, @thealphadollar :+1: 

- Dockerfile changes look good :heavy_check_mark: 
- Procedure described in the PR description looks good :heavy_check_mark: 
- Test suite failed (after restart) [here][1] :x: 
- Trying to build the docker images locally also threw the same error as the test suite:

```sh
$ docker-compose build
...
...
+ mv MultimediaViewer /srv/mediawiki/extensions/
mv: cannot move 'MultimediaViewer' to '/srv/mediawiki/extensions/MultimediaViewer': Directory not empty
ERROR: Service 'mediawiki' failed to build: The command '/bin/sh -c /tmp/install_extensions.sh' returned a non-zero code: 1
```

We need to investigate and fix this.

[1]: https://travis-ci.org/metakgp/metakgp-wiki/jobs/546100371#L725

**Review by icyflame — CHANGES_REQUESTED** [review]
We need to fix [this error][1].

[1]: https://travis-ci.org/metakgp/metakgp-wiki/jobs/546100371#L725

**Comment by amrav** [comment]
Looks like MultimediaViewer might be bundled with 1.32, in that case we
don't need to install it separately.

**Comment by thealphadollar** [comment]
> This extension comes with MediaWiki 1.31 and above. Thus you do not have to download it again. However, you still need to follow the other instructions provided.

This can be found as a notice on [MultimediaViewer's page](https://www.mediawiki.org/wiki/Extension:MultimediaViewer/en).

I'll remove it from downloads. Everything else remains the same.

**Comment by thealphadollar** [comment]
@icyflame @amrav I've updated the PR; have a look please.

I've updated lua path as well since it has been changed.

`chmod a+x /path/to/extensions/Scribunto/includes/engines/LuaStandalone/binaries/yourOS/lua`

Reference: https://www.mediawiki.org/wiki/Extension:Scribunto#Bundled_binaries

**Review by amrav — APPROVED** [review]
Looks good, thanks for doing this!

**Review by icyflame — APPROVED** [review]
LGTM!

- `docker-compose build` locally :white_check_mark: 
- `docker-compose up` and `http://localhost` works as expected; pages work well too.

**Pull request merged**
